// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: addons.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddon = `-- name: CreateAddon :one
INSERT INTO addons (
    id, module, name, description, price, unit, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, module, name, description, price, unit, is_active, created_at, updated_at
`

type CreateAddonParams struct {
	ID          string         `json:"id"`
	Module      string         `json:"module"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Unit        *string        `json:"unit"`
	IsActive    *bool          `json:"is_active"`
}

func (q *Queries) CreateAddon(ctx context.Context, arg CreateAddonParams) (Addon, error) {
	row := q.db.QueryRow(ctx, createAddon,
		arg.ID,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Unit,
		arg.IsActive,
	)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddon = `-- name: DeleteAddon :exec
DELETE FROM addons WHERE id = $1::varchar
`

func (q *Queries) DeleteAddon(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, deleteAddon, dollar_1)
	return err
}

const getActiveAddons = `-- name: GetActiveAddons :many
SELECT id, module, name, description, price, unit, is_active, created_at, updated_at FROM addons
WHERE is_active = true
  AND ($1::text = '' OR module = $1)
ORDER BY module ASC, price ASC
`

func (q *Queries) GetActiveAddons(ctx context.Context, dollar_1 string) ([]Addon, error) {
	rows, err := q.db.Query(ctx, getActiveAddons, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Addon{}
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAddonByID = `-- name: GetAddonByID :one
SELECT id, module, name, description, price, unit, is_active, created_at, updated_at FROM addons
WHERE id = $1::varchar LIMIT 1
`

func (q *Queries) GetAddonByID(ctx context.Context, dollar_1 string) (Addon, error) {
	row := q.db.QueryRow(ctx, getAddonByID, dollar_1)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddonsByIDs = `-- name: GetAddonsByIDs :many
SELECT id, module, name, description, price, unit, is_active, created_at, updated_at FROM addons
WHERE id = ANY($1::varchar[])
`

func (q *Queries) GetAddonsByIDs(ctx context.Context, dollar_1 []string) ([]Addon, error) {
	rows, err := q.db.Query(ctx, getAddonsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Addon{}
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAddons = `-- name: ListAllAddons :many
SELECT id, module, name, description, price, unit, is_active, created_at, updated_at FROM addons
WHERE ($1::text = '' OR module = $1)
ORDER BY module ASC, created_at DESC
`

func (q *Queries) ListAllAddons(ctx context.Context, dollar_1 string) ([]Addon, error) {
	rows, err := q.db.Query(ctx, listAllAddons, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Addon{}
	for rows.Next() {
		var i Addon
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAddonActive = `-- name: ToggleAddonActive :one
UPDATE addons
SET is_active = NOT is_active,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, price, unit, is_active, created_at, updated_at
`

func (q *Queries) ToggleAddonActive(ctx context.Context, dollar_1 string) (Addon, error) {
	row := q.db.QueryRow(ctx, toggleAddonActive, dollar_1)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAddon = `-- name: UpdateAddon :one
UPDATE addons
SET
    module = $2,
    name = $3,
    description = $4,
    price = $5,
    unit = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, price, unit, is_active, created_at, updated_at
`

type UpdateAddonParams struct {
	Column1     string         `json:"column_1"`
	Module      string         `json:"module"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Unit        *string        `json:"unit"`
	IsActive    *bool          `json:"is_active"`
}

func (q *Queries) UpdateAddon(ctx context.Context, arg UpdateAddonParams) (Addon, error) {
	row := q.db.QueryRow(ctx, updateAddon,
		arg.Column1,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Unit,
		arg.IsActive,
	)
	var i Addon
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
