// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBookings = `-- name: CountBookings :one
SELECT COUNT(*) FROM bookings
`

func (q *Queries) CountBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBookings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one

INSERT INTO bookings (
    id, package_id, customer_name, customer_email, customer_phone,
    customer_notes, status, total_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at
`

type CreateBookingParams struct {
	ID            string         `json:"id"`
	PackageID     string         `json:"package_id"`
	CustomerName  string         `json:"customer_name"`
	CustomerEmail string         `json:"customer_email"`
	CustomerPhone string         `json:"customer_phone"`
	CustomerNotes *string        `json:"customer_notes"`
	Status        string         `json:"status"`
	TotalPrice    pgtype.Numeric `json:"total_price"`
}

// =====================================================
// BOOKING QUERIES
// =====================================================
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.PackageID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.CustomerNotes,
		arg.Status,
		arg.TotalPrice,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerNotes,
		&i.PaymentScreenshotUrl,
		&i.Status,
		&i.TotalPrice,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingAddon = `-- name: CreateBookingAddon :one

INSERT INTO booking_addons (
    booking_id, addon_id, quantity
) VALUES (
    $1, $2, $3
) RETURNING id, booking_id, addon_id, quantity, created_at
`

type CreateBookingAddonParams struct {
	BookingID string `json:"booking_id"`
	AddonID   string `json:"addon_id"`
	Quantity  int32  `json:"quantity"`
}

// =====================================================
// BOOKING ADDONS QUERIES
// =====================================================
func (q *Queries) CreateBookingAddon(ctx context.Context, arg CreateBookingAddonParams) (BookingAddon, error) {
	row := q.db.QueryRow(ctx, createBookingAddon, arg.BookingID, arg.AddonID, arg.Quantity)
	var i BookingAddon
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AddonID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createBookingSlot = `-- name: CreateBookingSlot :one

INSERT INTO booking_slots (
    booking_id, date, time, theme_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, booking_id, date, time, theme_id, created_at
`

type CreateBookingSlotParams struct {
	BookingID string      `json:"booking_id"`
	Date      pgtype.Date `json:"date"`
	Time      pgtype.Time `json:"time"`
	ThemeID   string      `json:"theme_id"`
}

// =====================================================
// BOOKING SLOTS QUERIES
// =====================================================
func (q *Queries) CreateBookingSlot(ctx context.Context, arg CreateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRow(ctx, createBookingSlot,
		arg.BookingID,
		arg.Date,
		arg.Time,
		arg.ThemeID,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Date,
		&i.Time,
		&i.ThemeID,
		&i.CreatedAt,
	)
	return i, err
}

const getBookedSlotsForAllThemesAndDate = `-- name: GetBookedSlotsForAllThemesAndDate :many
SELECT bs.id, bs.booking_id, bs.date, bs.time, bs.theme_id, bs.created_at FROM booking_slots bs
INNER JOIN bookings b ON bs.booking_id = b.id
WHERE bs.date = $1
  AND b.status IN ('PENDING', 'APPROVED')
ORDER BY bs.time
`

func (q *Queries) GetBookedSlotsForAllThemesAndDate(ctx context.Context, date pgtype.Date) ([]BookingSlot, error) {
	rows, err := q.db.Query(ctx, getBookedSlotsForAllThemesAndDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSlot{}
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Date,
			&i.Time,
			&i.ThemeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookedSlotsForThemeAndDate = `-- name: GetBookedSlotsForThemeAndDate :many
SELECT bs.id, bs.booking_id, bs.date, bs.time, bs.theme_id, bs.created_at FROM booking_slots bs
INNER JOIN bookings b ON bs.booking_id = b.id
WHERE bs.theme_id = $1::varchar
  AND bs.date = $2
  AND b.status IN ('PENDING', 'APPROVED')
ORDER BY bs.time
`

type GetBookedSlotsForThemeAndDateParams struct {
	Column1 string      `json:"column_1"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) GetBookedSlotsForThemeAndDate(ctx context.Context, arg GetBookedSlotsForThemeAndDateParams) ([]BookingSlot, error) {
	rows, err := q.db.Query(ctx, getBookedSlotsForThemeAndDate, arg.Column1, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSlot{}
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Date,
			&i.Time,
			&i.ThemeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingAddons = `-- name: GetBookingAddons :many
SELECT id, booking_id, addon_id, quantity, created_at FROM booking_addons
WHERE booking_id = $1::varchar
`

func (q *Queries) GetBookingAddons(ctx context.Context, dollar_1 string) ([]BookingAddon, error) {
	rows, err := q.db.Query(ctx, getBookingAddons, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingAddon{}
	for rows.Next() {
		var i BookingAddon
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.AddonID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at FROM bookings
WHERE id = $1::varchar LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, dollar_1 string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, dollar_1)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerNotes,
		&i.PaymentScreenshotUrl,
		&i.Status,
		&i.TotalPrice,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingSlots = `-- name: GetBookingSlots :many
SELECT id, booking_id, date, time, theme_id, created_at FROM booking_slots
WHERE booking_id = $1::varchar
ORDER BY date, time
`

func (q *Queries) GetBookingSlots(ctx context.Context, dollar_1 string) ([]BookingSlot, error) {
	rows, err := q.db.Query(ctx, getBookingSlots, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingSlot{}
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Date,
			&i.Time,
			&i.ThemeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByCustomerEmail = `-- name: GetBookingsByCustomerEmail :many
SELECT id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at FROM bookings
WHERE customer_email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingsByCustomerEmail(ctx context.Context, customerEmail string) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByCustomerEmail, customerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.CustomerNotes,
			&i.PaymentScreenshotUrl,
			&i.Status,
			&i.TotalPrice,
			&i.AdminNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingsByStatus = `-- name: GetBookingsByStatus :many
SELECT id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at FROM bookings
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingsByStatus(ctx context.Context, status string) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.CustomerNotes,
			&i.PaymentScreenshotUrl,
			&i.Status,
			&i.TotalPrice,
			&i.AdminNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at FROM bookings
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBookingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.CustomerNotes,
			&i.PaymentScreenshotUrl,
			&i.Status,
			&i.TotalPrice,
			&i.AdminNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingPaymentScreenshot = `-- name: UpdateBookingPaymentScreenshot :one
UPDATE bookings
SET
    payment_screenshot_url = $2,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at
`

type UpdateBookingPaymentScreenshotParams struct {
	Column1              string  `json:"column_1"`
	PaymentScreenshotUrl *string `json:"payment_screenshot_url"`
}

func (q *Queries) UpdateBookingPaymentScreenshot(ctx context.Context, arg UpdateBookingPaymentScreenshotParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingPaymentScreenshot, arg.Column1, arg.PaymentScreenshotUrl)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerNotes,
		&i.PaymentScreenshotUrl,
		&i.Status,
		&i.TotalPrice,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET
    status = $2,
    admin_notes = $3,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, package_id, customer_name, customer_email, customer_phone, customer_notes, payment_screenshot_url, status, total_price, admin_notes, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	Column1    string  `json:"column_1"`
	Status     string  `json:"status"`
	AdminNotes *string `json:"admin_notes"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.Column1, arg.Status, arg.AdminNotes)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerNotes,
		&i.PaymentScreenshotUrl,
		&i.Status,
		&i.TotalPrice,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
