// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Addon struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Unit        *string            `json:"unit"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID                   string             `json:"id"`
	PackageID            string             `json:"package_id"`
	CustomerName         string             `json:"customer_name"`
	CustomerEmail        string             `json:"customer_email"`
	CustomerPhone        string             `json:"customer_phone"`
	CustomerNotes        *string            `json:"customer_notes"`
	PaymentScreenshotUrl *string            `json:"payment_screenshot_url"`
	Status               string             `json:"status"`
	TotalPrice           pgtype.Numeric     `json:"total_price"`
	AdminNotes           *string            `json:"admin_notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BookingAddon struct {
	ID        int32              `json:"id"`
	BookingID string             `json:"booking_id"`
	AddonID   string             `json:"addon_id"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BookingSlot struct {
	ID        int32              `json:"id"`
	BookingID string             `json:"booking_id"`
	Date      pgtype.Date        `json:"date"`
	Time      pgtype.Time        `json:"time"`
	ThemeID   string             `json:"theme_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Package struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	Discount        pgtype.Numeric     `json:"discount"`
	Offers          []byte             `json:"offers"`
	ImageUrl        *string            `json:"image_url"`
	IsActive        *bool              `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Theme struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	Price       pgtype.Numeric     `json:"price"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        *string            `json:"phone"`
	Role         string             `json:"role"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
