// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (
    id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at
`

type CreatePackageParams struct {
	ID              string         `json:"id"`
	Module          string         `json:"module"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	DurationMinutes int32          `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	Discount        pgtype.Numeric `json:"discount"`
	Offers          []byte         `json:"offers"`
	ImageUrl        *string        `json:"image_url"`
	IsActive        *bool          `json:"is_active"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.ID,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.Price,
		arg.Discount,
		arg.Offers,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.Discount,
		&i.Offers,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :exec
DELETE FROM packages WHERE id = $1::varchar
`

func (q *Queries) DeletePackage(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, deletePackage, dollar_1)
	return err
}

const getActivePackages = `-- name: GetActivePackages :many
SELECT id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at FROM packages
WHERE is_active = true
  AND ($1::text = '' OR module = $1)
ORDER BY module ASC, price ASC
`

func (q *Queries) GetActivePackages(ctx context.Context, dollar_1 string) ([]Package, error) {
	rows, err := q.db.Query(ctx, getActivePackages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.Price,
			&i.Discount,
			&i.Offers,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at FROM packages
WHERE id = $1::varchar LIMIT 1
`

func (q *Queries) GetPackageByID(ctx context.Context, dollar_1 string) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByID, dollar_1)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.Discount,
		&i.Offers,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPackages = `-- name: ListAllPackages :many
SELECT id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at FROM packages
WHERE ($1::text = '' OR module = $1)
ORDER BY module ASC, created_at DESC
`

func (q *Queries) ListAllPackages(ctx context.Context, dollar_1 string) ([]Package, error) {
	rows, err := q.db.Query(ctx, listAllPackages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.Price,
			&i.Discount,
			&i.Offers,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePackageActive = `-- name: TogglePackageActive :one
UPDATE packages
SET is_active = NOT is_active,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at
`

func (q *Queries) TogglePackageActive(ctx context.Context, dollar_1 string) (Package, error) {
	row := q.db.QueryRow(ctx, togglePackageActive, dollar_1)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.Discount,
		&i.Offers,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
SET
    module = $2,
    name = $3,
    description = $4,
    duration_minutes = $5,
    price = $6,
    discount = $7,
    offers = $8,
    image_url = $9,
    is_active = $10,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at
`

type UpdatePackageParams struct {
	Column1         string         `json:"column_1"`
	Module          string         `json:"module"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	DurationMinutes int32          `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	Discount        pgtype.Numeric `json:"discount"`
	Offers          []byte         `json:"offers"`
	ImageUrl        *string        `json:"image_url"`
	IsActive        *bool          `json:"is_active"`
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.Column1,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.Price,
		arg.Discount,
		arg.Offers,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.Discount,
		&i.Offers,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePackageImageURL = `-- name: UpdatePackageImageURL :one
UPDATE packages
SET
    image_url = $2,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, duration_minutes, price, discount, offers, image_url, is_active, created_at, updated_at
`

type UpdatePackageImageURLParams struct {
	Column1  string  `json:"column_1"`
	ImageUrl *string `json:"image_url"`
}

func (q *Queries) UpdatePackageImageURL(ctx context.Context, arg UpdatePackageImageURLParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackageImageURL, arg.Column1, arg.ImageUrl)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.Discount,
		&i.Offers,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
