// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: themes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (
    id, module, name, description, image_url, price, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, module, name, description, image_url, price, is_active, created_at, updated_at
`

type CreateThemeParams struct {
	ID          string         `json:"id"`
	Module      string         `json:"module"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    string         `json:"image_url"`
	Price       pgtype.Numeric `json:"price"`
	IsActive    *bool          `json:"is_active"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme,
		arg.ID,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Price,
		arg.IsActive,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM themes WHERE id = $1::varchar
`

func (q *Queries) DeleteTheme(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, deleteTheme, dollar_1)
	return err
}

const getActiveThemes = `-- name: GetActiveThemes :many
SELECT id, module, name, description, image_url, price, is_active, created_at, updated_at FROM themes
WHERE is_active = true
  AND ($1::text = '' OR module = $1)
ORDER BY module ASC, name ASC
`

func (q *Queries) GetActiveThemes(ctx context.Context, dollar_1 string) ([]Theme, error) {
	rows, err := q.db.Query(ctx, getActiveThemes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThemeByID = `-- name: GetThemeByID :one
SELECT id, module, name, description, image_url, price, is_active, created_at, updated_at FROM themes
WHERE id = $1::varchar LIMIT 1
`

func (q *Queries) GetThemeByID(ctx context.Context, dollar_1 string) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeByID, dollar_1)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, module, name, description, image_url, price, is_active, created_at, updated_at FROM themes
WHERE ($1::text = '' OR module = $1)
ORDER BY module ASC, created_at DESC
`

func (q *Queries) ListAllThemes(ctx context.Context, dollar_1 string) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleThemeActive = `-- name: ToggleThemeActive :one
UPDATE themes
SET is_active = NOT is_active,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, image_url, price, is_active, created_at, updated_at
`

func (q *Queries) ToggleThemeActive(ctx context.Context, dollar_1 string) (Theme, error) {
	row := q.db.QueryRow(ctx, toggleThemeActive, dollar_1)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTheme = `-- name: UpdateTheme :one
UPDATE themes
SET
    module = $2,
    name = $3,
    description = $4,
    image_url = $5,
    price = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, image_url, price, is_active, created_at, updated_at
`

type UpdateThemeParams struct {
	Column1     string         `json:"column_1"`
	Module      string         `json:"module"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageUrl    string         `json:"image_url"`
	Price       pgtype.Numeric `json:"price"`
	IsActive    *bool          `json:"is_active"`
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateTheme,
		arg.Column1,
		arg.Module,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Price,
		arg.IsActive,
	)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThemeImageURL = `-- name: UpdateThemeImageURL :one
UPDATE themes
SET
    image_url = $2,
    updated_at = NOW()
WHERE id = $1::varchar
RETURNING id, module, name, description, image_url, price, is_active, created_at, updated_at
`

type UpdateThemeImageURLParams struct {
	Column1  string `json:"column_1"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) UpdateThemeImageURL(ctx context.Context, arg UpdateThemeImageURLParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateThemeImageURL, arg.Column1, arg.ImageUrl)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
